# Generated by Django 4.1.1 on 2022-09-14 20:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autocompany', '0003_cart_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='parts',
            field=models.CharField(max_length=1000, validators=[django.core.validators.int_list_validator]),
        ),
        migrations.AlterField(
            model_name='order',
            name='parts',
            field=models.CharField(max_length=1000, validators=[django.core.validators.int_list_validator]),
        ),
    ]
