# Generated by Django 4.0.3 on 2022-09-16 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autocompany', '0005_alter_order_delivery_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='part',
            name='price',
            field=models.FloatField(null=True),
        ),
    ]
